import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as cwActions from 'aws-cdk-lib/aws-cloudwatch-actions';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as sns from 'aws-cdk-lib/aws-sns';

export interface OpsAlarmsStackProps extends cdk.StackProps {
  /** The app ALB (AppStack) — source of the ELB 5xx metric. */
  readonly alb: elbv2.IApplicationLoadBalancer;
  /** The app target group (AppStack) — source of HealthyHostCount. */
  readonly targetGroup: elbv2.IApplicationTargetGroup;
}

/**
 * OpsAlarmsStack: operational CloudWatch alarms for the deployed dashboard.
 *
 *  1. Collector Lambda Errors  — >= 1 error in 3 consecutive 5-min periods
 *     (the collector runs every 5 min, so 3 periods = 3 missed collections).
 *  2. ALB HealthyHostCount < 1 — reliable ECS-liveness signal without
 *     Container Insights: if no target is healthy, the app is down.
 *  3. ALB ELB 5xx > 10 / 5 min — errors generated by the ALB itself
 *     (no healthy target, connection failures) reaching viewers.
 *
 * All alarms notify the `nfm-dashboard-alarms` SNS topic on both ALARM and
 * OK. Subscriptions are intentionally NOT created here — the operator
 * subscribes out-of-band, e.g.:
 *   aws sns subscribe --topic-arn <AlarmTopicArn output> \
 *     --protocol email --notification-endpoint you@example.com
 */
export class OpsAlarmsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: OpsAlarmsStackProps) {
    super(scope, id, props);

    const topic = new sns.Topic(this, 'AlarmTopic', {
      topicName: 'nfm-dashboard-alarms',
      displayName: 'nfm-dashboard operational alarms',
    });

    const collectorErrors = new cloudwatch.Alarm(this, 'CollectorErrors', {
      alarmName: 'nfm-dashboard-collector-errors',
      alarmDescription:
        'Collector Lambda (nfm-dashboard-collector) errored in 3 consecutive ' +
        '5-minute periods — flow/monitor data is no longer being ingested.',
      metric: new cloudwatch.Metric({
        namespace: 'AWS/Lambda',
        metricName: 'Errors',
        // By name, not construct ref: the function lives in NfmDash-Data and
        // its physical name is pinned there (functionName). No cross-stack
        // coupling to DataStack needed for a metric dimension.
        dimensionsMap: { FunctionName: 'nfm-dashboard-collector' },
        statistic: 'Sum',
        period: cdk.Duration.minutes(5),
      }),
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
      threshold: 1,
      evaluationPeriods: 3,
      // No invocations in a period → no Errors datapoint; that is not a failure.
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    const noHealthyHosts = new cloudwatch.Alarm(this, 'NoHealthyHosts', {
      alarmName: 'nfm-dashboard-alb-no-healthy-hosts',
      alarmDescription:
        'ALB target group has no healthy app task (HealthyHostCount < 1 for ' +
        '3 consecutive minutes) — the dashboard is unreachable. Liveness proxy ' +
        'for the ECS service (Container Insights not enabled).',
      metric: props.targetGroup.metrics.healthyHostCount({
        statistic: 'Minimum',
        period: cdk.Duration.minutes(1),
      }),
      comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
      threshold: 1,
      evaluationPeriods: 3,
      // HealthyHostCount is emitted continuously; if it goes missing the ALB
      // itself is broken — treat that as an incident too.
      treatMissingData: cloudwatch.TreatMissingData.BREACHING,
    });

    const alb5xx = new cloudwatch.Alarm(this, 'Alb5xx', {
      alarmName: 'nfm-dashboard-alb-5xx',
      alarmDescription:
        'ALB generated more than 10 ELB 5xx responses in 5 minutes — viewers ' +
        'are receiving errors (no healthy target / connection failures).',
      metric: props.alb.metrics.httpCodeElb(elbv2.HttpCodeElb.ELB_5XX_COUNT, {
        statistic: 'Sum',
        period: cdk.Duration.minutes(5),
      }),
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      threshold: 10,
      evaluationPeriods: 1,
      // The metric is only emitted when 5xx occur — missing means healthy.
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    for (const alarm of [collectorErrors, noHealthyHosts, alb5xx]) {
      alarm.addAlarmAction(new cwActions.SnsAction(topic));
      alarm.addOkAction(new cwActions.SnsAction(topic)); // recovery notice
    }

    new cdk.CfnOutput(this, 'AlarmTopicArn', { value: topic.topicArn });
  }
}
